config/routes.rb
                member do
                    get 'resend-confirmation', to: 'user_setups#resend_confirmation'
                end
                resources :audits, only: [:index, :show]
            end

            # append single get route before organizations/:id catch
            get 'organizations/chart', to: 'organizations#chart'
            get 'organizations/tree', to: 'organizations#tree'
            resources :organizations do
                resources :audits, only: [:index, :show]
            end

            resources :template_variables do
                resources :audits, only: [:index, :show]
            end

            resources :job_types do
                resources :audits, only: [:index, :show]
            end

            resources :laboratory_types do
                resources :audits, only: [:index, :show]
            end

            resources :call_log_case_types do
                resources :audits, only: [:index, :show]
            end

            resources :titles do
                resources :audits, only: [:index, :show]
            end

            resources :fp_devices

            resources :district_health_offices do
                resources :audits, only: [:index, :show]
            end

            resources :employer_types do
                resources :audits, only: [:index, :show]
            end

            resources :appeal_todos do
                resources :audits, only: [:index, :show]
            end

            resources :tcupi_todos do
                resources :audits, only: [:index, :show]
            end

            resources :digital_xray_providers do
                resources :audits, only: [:index, :show]
            end

            resources :insurance_service_providers do
                resources :audits, only: [:index, :show]
            end

            resources :finance_settings do
                resources :audits, only: [:index, :show]
            end

            resources :races do
                resources :audits, only: [:index, :show]
            end

            resources :approval_approvers do
                resources :audits, only: [:index, :show]
            end

            get 'approval_approvers/:category/category_approvers', to: '/internal/approval_approvers#category_approvers', as: "category_approvers"

            resources :bulletins
            resources :clinics
            resources :xray_dispatches
            resources :xray_storages
            resources :activities, only: [:index]

            resources :call_logs do
                collection do
                    get "search_callable"
                end
                resources :call_log_follow_ups
            end

            resources :bank_drafts do
                member do
                    get 'hold'
                    post 'hold', to: 'bank_drafts#hold_update'
                    get 'unhold'
                    patch 'unhold', to: 'bank_drafts#unhold_update'

                    get 'bad'
                    get 'unbad'

                    get 'replace'
                    patch 'replace', to: 'bank_drafts#replace_update'

                    get 'refund'
                    patch 'refund', to: 'bank_drafts#refund_update'
                end

                resources :bd_refunds
            end

            resources :orders do
                member do
                    get 'approval'
                    patch 'approval', to: 'orders#approval_update'

                    get 'payment'
                    patch 'payment', to: 'orders#payment_update'

                    get 'payment/bankdraft', to: 'orders#payment_bankdraft'
                    get 'payment/bankdraft/new', to: 'orders#payment_bankdraft_new'
                    put 'payment/bankdraft', to: 'orders#payment_bankdraft_create'
                    get 'payment/bankdraft/:bank_draft_id/edit', to: 'orders#payment_bankdraft_edit', as: "payment_bankdraft_edit"
                    patch 'payment/bankdraft/:bank_draft_id', to: 'orders#payment_bankdraft_update', as: "payment_bankdraft_update"
                    delete 'payment/bankdraft/:bank_draft_id', to: 'orders#payment_bankdraft_destroy', as: "payment_bankdraft_destroy"
                    get 'payment/bankdraft/:bank_draft_id/add', to: 'orders#payment_bankdraft_add', as: "payment_bankdraft_add"
                    put 'payment/bankdraft/:bank_draft_id/add', to: 'orders#payment_bankdraft_add_update'

                    post 'payment_status'
                    post 'payment_status_backend'

                    post 'change_comment', to: 'orders#change_comment', as: 'change_comment'
                    post 'change_fee', to: 'orders#change_fee', as: 'change_fee'
                    post 'add_fw', to: 'orders#add_fw', as: 'add_fw'
                    get 'remove_fw', to: 'orders#remove_fw', as: 'remove_fw'
                    patch 'update_fw', to: 'orders#update_fw', as: 'update_fw'

                    get "remove-order-item/:oi_id", to: "orders#remove_order_item", as: "remove_order_item"

                    get 'invoice', to: 'orders#invoice', as: 'invoice'

                    get 'requery', to: 'orders#requery', as: 'requery'
                    get 'requery/fpx_request', to: 'orders#requery_fpx_request', as: 'requery_fpx_request'
                    get 'payment/fpxrequest/:fpx_request_id', to: 'orders#requery_fpx_request_ae', as: 'requery_fpx_request_ae'
                    get 'edit_status', to: 'orders#edit_status', as: 'edit_status'
                    patch 'edit_status_update', to: 'orders#edit_status_update', as: 'edit_status_update'
                    get 'requery/boleh_request', to: 'orders#requery_boleh_request', as: 'requery_boleh_request'
                    get 'payment/bolehrequest/:boleh_request_id', to: 'orders#requery_boleh_request_ae', as: 'requery_boleh_request_ae'
                end
                resources :audits, only: [:index, :show]
            end

            resources :refunds do
                member do
                    get 'draft'
                    get 'approval'
                    patch 'approval', to: 'refunds#approval_update'
                    get 'cancel'
                    get 'status'
                    patch 'status', to: 'refunds#status_update'
                    get 'credit_note'
                    post 'reprocess', to: 'refunds#reprocess', as: 'reprocess'
                end

                collection do
                    post 'bulk', to: 'refunds#bulk'

                    get 'export', to: 'refunds#export', as: 'export'
                end

                resources :audits, only: [:index, :show]
            end

            ## refund batches
            resources :refund_batches do
                member do
                    get 'process', to: 'refund_batches#process_payment', as: 'process'
                    get 'download', to: 'refund_batches#download', as: 'download'
                end
            end

            resources :drafts, only: [:index, :show] do
                get :submit_for_approval
            end

            # service provider payments
            scope 'payments', as: 'payments' do
                get '/', to: 'service_provider_payments#index'
                get ':id/batches', to: 'service_provider_payments#show', as: 'batch_show'
                get 'new', to: 'service_provider_payments#new', as: 'batch_new'

                get 'get_batches', to:'service_provider_payments#get_batches'

                get 'bulk_update_template', to: 'service_provider_payments#bulk_update_template', as: 'bulk_update_template'
                post 'generate_batch', to:'service_provider_payments#create', as: 'batch_create'
                post 'bulk_update/:id', to:'service_provider_payments#bulk_update', as: 'bulk_update'
                get 'reprocess/:id', to: 'service_provider_payments#reprocess', as: 'reprocess'
                get 'process/:id', to: 'service_provider_payments#process_payment', as: 'process'

                # export data
                get ':id/export', to: 'service_provider_payments#export', as: 'export'
            end
            #end

            scope 'manual_payment', as: 'manual_payment' do
                get "/", to: "service_provider_payments#view_transactions", as: "view_transactions"
                get ":id/edit_payment_xray", to: "service_provider_payments#edit_payment_xray", as: "edit_payment_xray"
                post ":id/update_payment", to: "service_provider_payments#update_payment", as: "update_payment"
                get ":id/edit_payment_lab", to: "service_provider_payments#edit_payment_lab", as: "edit_payment_lab"
                get ":id/view_payment_xray", to: "service_provider_payments#view_payment_xray", as: "view_payment_xray"
                get ":id/view_payment_lab", to: "service_provider_payments#view_payment_lab", as: "view_payment_lab"

                get ":id/view_payment_doctor", to: "service_provider_payments#view_payment_doctor", as: "view_payment_doctor"
                get ":id/edit_payment_doctor", to: "service_provider_payments#edit_payment_doctor", as: "edit_payment_doctor"

                get "/export",to: "service_provider_payments#export_manual_payment", as: "export_manual_payment"
            end

            scope 'payment_listing', as: 'payment_listing' do
                get "/", to: "service_provider_payments#view_payment_listing", as: "view_payment_listing"
                get '/export', to: 'service_provider_payments#export_payment_listing', as: 'export_payment_listing'
            end

            resources :insurance_payments do
                member do
                    post 'process', to: 'insurance_payments#process_payment', as: 'process'
                    get 'export', to: 'insurance_payments#export', as: 'export'
                end
            end

            resources :agencies do
                collection do

app/views/internal/orders/special_transaction_registrations/_foc.html.erb
<% 
foreign_worker = order_item.order_itemable
foreign_worker.assign_attributes(order_item.additional_information["foreign_worker"]) if !order_item.additional_information.blank? and order_item.additional_information.key?("foreign_worker")
@has_plks_optional = true if order_item.order_itemable.plks_optional? %>

<tr class="<%= "plks-optional" if order_item.order_itemable.plks_optional? %>">
   <!-- <td><input type="checkbox" class="bulk" name="addon_foreign_worker_ids[]" value="<%= order_item.order_itemable.id %>"></td> -->
    <td><a href="<%= internal_employer_employer_worker_path(foreign_worker.employer, foreign_worker) %>" target="_blank"><%= foreign_worker.name %></a>
      <button class="btn btn-sm btn-warning" type="button" style="float: right;" data-toggle="modal" data-target="#modal-fw-<%= order_item.order_itemable_id %>">Edit</button>
    </td>
    <td><%= ForeignWorker::GENDERS[order_item&.gender] %></td>
     <td><pre><%= order_item.additional_information["comments"] %></pre></td>
    <td><%= order_item.order_itemable.plks_number.to_i %></td>
     <td><textarea name="comment[<%= order_item.id %>]" id="comment_<%= order_item.id %>" data-order_item_id="<%= order_item.id %>" class="form-control" required onblur="comment_changed(this)"><%= order_item.comment %></textarea></td>
    <td><% if has_permission?("CREATE_FOC_TRANSACTION") %>
             <%= select_tag("fee", options_from_collection_for_select(Fee.select("id, name || ' (' || amount || ')' as label").where("code in (?)", ["TRANSACTION_#{ForeignWorker::GENDERS[order_item&.gender]}", "FOC"]), :id, :label, order_item.fee_id), class: "form-control", onchange: "change_fee(this)", data: {order_item_id: order_item.id}) %>
        <% else %>
            <%= number_to_currency(order_item.amount, unit: "") %>
        <% end %>
    </td>   
    <td class="text-right">
        <input type="hidden" name="foreign_worker_ids[]" value="<%= order_item.order_itemable.id %>" class="etr-foreign_workers" data-amount="<%= order_item.amount %>">
        <button type="button" class="btn btn-sm btn-secondary" onclick="etr_remove(this)">X</button>
    </td>
    <td></td>  
</tr>

app/views/internal/orders/special_transaction_registrations/_insurance_adminfees.html.erb
<% if order_item.amount > 0 %>
<tr>
    <td>&nbsp;</td>
    <td colspan="2"><%= "#{order_item.fee.name}" %></td>
    <td class="currency"><%= number_to_currency(order_item.amount, unit: "") %></td>
    <td>&nbsp;</td>
</tr>
<% end %>

app/views/internal/orders/special_transaction_registrations/_insurance_adminfees_sst.html.erb
<% if order_item.amount > 0 %>
<tr>
    <td>&nbsp;</td>
    <td colspan="2"><%= "#{order_item.fee.name}" %></td>
    <td class="currency"><%= number_to_currency(order_item.amount, unit: "") %></td>
    <td>&nbsp;</td>
</tr>
<% end %>

app/views/internal/orders/special_transaction_registrations/_insurance_gross_premium.html.erb
<tr>
     <td><%= "#{order_item.order_itemable.name} - #{order_item.fee.name} #{"(#{order_item.insurance_purchase.insurance_provider})" if order_item.insurance_purchase}" %></td>
    <td colspan="4">&nbsp;</td>
    <td class="currency"><%= order_item.insurance_purchase&.total_premium ? number_to_currency(order_item.insurance_purchase&.total_premium, unit: "") : '-' %></td>
    <td class="order-item-actions text-right">
        <a class="btn btn-sm btn-secondary" href="<%= remove_order_item_internal_order_path(order_item.order_id, order_item.id) %>">X</a>
    </td>
    
</tr>

app/views/internal/orders/special_transaction_registrations/_insurance_sst.html.erb
<% if order_item.amount > 0 %>
<tr>
    <td>&nbsp;</td>
    <td colspan="2"><%= "#{order_item.fee.name}" %></td>
    <td class="currency"><%= number_to_currency(order_item.amount, unit: "") %></td>
    <td>&nbsp;</td>
</tr>
<% end %>

app/views/internal/orders/special_transaction_registrations/_insurance_stamp_duty.html.erb
<% if order_item.amount > 0 %>
<tr>
    <td>&nbsp;</td>
    <td colspan="2"><%= "#{order_item.fee.name}" %></td>
    <td class="currency"><%= number_to_currency(order_item.amount, unit: "") %></td>
    <td>&nbsp;</td>
</tr>
<% end %>

app/views/internal/orders/special_transaction_registrations/_transaction_female.html.erb
<% 
foreign_worker = order_item.order_itemable
foreign_worker.assign_attributes(order_item.additional_information["foreign_worker"]) if !order_item.additional_information.blank? and order_item.additional_information.key?("foreign_worker")
@has_plks_optional = true if order_item.order_itemable.plks_optional? %>

<tr class="<%= "plks-optional" if order_item.order_itemable.plks_optional? %>">
  <!--<<td><input type="checkbox" class="bulk" name="addon_foreign_worker_ids[]" value="<%= order_item.order_itemable.id %>"></td>-->
    <td><a href="<%= internal_employer_employer_worker_path(foreign_worker.employer, foreign_worker) %>" target="_blank"><%= foreign_worker.name %></a>
      <button class="btn btn-sm btn-warning" type="button" style="float: right;" data-toggle="modal" data-target="#modal-fw-<%= order_item.order_itemable_id %>">Edit</button>
    </td>
    <td><%= ForeignWorker::GENDERS[order_item&.gender] %></td>
    <td><pre><%= order_item.additional_information["comments"] %></pre></td>
    <td><%= order_item.order_itemable.plks_number.to_i %></td>
    <td><textarea name="comment[<%= order_item.id %>]" id="comment_<%= order_item.id %>" data-order_item_id="<%= order_item.id %>" class="form-control" required onblur="comment_changed(this)"><%= order_item.comment %></textarea></td>
    <td><% if has_permission?("CREATE_FOC_TRANSACTION") %>
             <%= select_tag("fee", options_from_collection_for_select(Fee.select("id, name || ' (' || amount || ')' as label").where("code in (?)", ["TRANSACTION_#{ForeignWorker::GENDERS[order_item&.gender]}", "FOC"]), :id, :label, order_item.fee_id), class: "form-control", onchange: "change_fee(this)", data: {order_item_id: order_item.id}) %>
        <% else %>
            <%= number_to_currency(order_item.amount, unit: "") %>
        <% end %>
    </td>   
    <td class="text-right">
        <input type="hidden" name="foreign_worker_ids[]" value="<%= order_item.order_itemable.id %>" class="etr-foreign_workers" data-amount="<%= order_item.amount %>">
        <button type="button" class="btn btn-sm btn-secondary" onclick="etr_remove(this)">X</button>
    </td>
    <td></td>  
</tr>

app/views/internal/orders/special_transaction_registrations/_transaction_male.html.erb
<%
foreign_worker = order_item.order_itemable
foreign_worker.assign_attributes(order_item.additional_information["foreign_worker"]) if !order_item.additional_information.blank? and order_item.additional_information.key?("foreign_worker")
@has_plks_optional = true if order_item.order_itemable.plks_optional? %>

<tr class="<%= "plks-optional" if order_item.order_itemable.plks_optional? %>">
  <!--<  <td> <input type="checkbox" class="bulk" name="addon_foreign_worker_ids[]" value="<%= order_item.order_itemable.id %>"></td> -->
    <td><a href="<%= internal_employer_employer_worker_path(foreign_worker.employer, foreign_worker) %>" target="_blank"><%= foreign_worker.name %></a>
      <button class="btn btn-sm btn-warning" type="button" style="float: right;" data-toggle="modal" data-target="#modal-fw-<%= order_item.order_itemable_id %>">Edit</button>
    </td>
    <td><%= ForeignWorker::GENDERS[order_item&.gender] %></td>
    <td><pre><%= order_item.additional_information["comments"] %></pre></td>
    <td><%= order_item.order_itemable.plks_number.to_i %></td>
    <td><% if has_permission?("CREATE_FOC_TRANSACTION") %>
             <%= select_tag("fee", options_from_collection_for_select(Fee.select("id, name || ' (' || amount || ')' as label").where("code in (?)", ["TRANSACTION_#{ForeignWorker::GENDERS[order_item&.gender]}", "FOC"]), :id, :label, order_item.fee_id), class: "form-control", onchange: "change_fee(this)", data: {order_item_id: order_item.id}) %>
        <% else %>
            <%= number_to_currency(order_item.amount, unit: "") %>
        <% end %>
    </td>
    <td class="text-right">
        <input type="hidden" name="foreign_worker_ids[]" value="<%= order_item.order_itemable.id %>" class="etr-foreign_workers" data-amount="<%= order_item.amount %>">
        <button type="button" class="btn btn-sm btn-secondary" onclick="etr_remove(this)">X</button>
    </td>
    <td></td>
</tr>

app/views/internal/orders/special_transaction_registrations/edit.html.erb
<% has_plks_optional = false %>

<div class="card">
    <!-- card-header -->
    <div class="card-header">
        Order - <%= @order.code %>
    </div>
    <!-- /card-header -->

    <%= form_for @order, url: external_order_path(@order), html: {id: "order_form"} do |form| %>
        <!-- card-body -->
        <div class="card-body">
            <%= render '/shared/all_flash' %>
            <%= render "internal/orders/shared/order_detail", {order: @order, form: form} %>

            <p class="plks-optional-message">
                Please review your worker list before submission. Workers highlighted in blue indicates that medical examination is optional for upcoming period. Your may choose to go ahead and register these workers for a medical or remove the workers.
            </p>

            <% if InsuranceService.order_has_insurance?(order: @order) %>
                <p class="order-warning-text">
                    Changes related to insurance premium require re-calculation. Kindly click on Calculate Insurance Premium button for re-calculation.
                </p>
            <% end %>

            <table class="table">
                <thead>
                    <tr>
                        <th>Foreign Worker</th>
                        <th>Gender</th>
                        <th>&nbsp;</th>
                        <th>PLKS</th>
                        <th>Amount</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <% @order.order_items.joins("join fees on order_items.fee_id = fees.id
                    left join foreign_workers on order_items.order_itemable_id = foreign_workers.id and order_items.order_itemable_type = 'ForeignWorker'")
                    .select("order_items.*, case when order_items.order_itemable_type = 'ForeignWorker' then 1
                    else 2 end as sort1, foreign_workers.name as sort2, case when fees.code in ('TRANSACTION_MALE', 'TRANSACTION_FEMALE') then 1
                    else 2 end as sort3")
                    .where.not("fees.code" => ["INSURANCE_SST", "INSURANCE_STAMP_DUTY", "INSURANCE_ADMINFEES", "INSURANCE_ADMINFEES_SST"])
                    .order("sort1 asc, sort2 asc, sort3 asc").includes(:fee, :order_itemable, :insurance_purchase).each do |order_item| %>
                        <%=render "internal/orders/special_transaction_registrations/#{order_item.fee.code.downcase}", {order_item: order_item} %>
                    <% end %>
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="5">&nbsp;</th>
                        <th class="currency">
                            <div class="etr-amount-total"><%= number_to_currency(@order.amount, unit: "") %></div>
                        </th>
                        <th>&nbsp;</th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <!-- /card-body -->

        <div class="card-footer">
            <div class="text-right">
                <% if has_permission?("CREATE_INSURANCE_PURCHASE") %>
                    <button class="btn btn-primary" type="submit" name="submit" value="addon_insurance" id="btn-addon_insurance" formnovalidate>Add-on Insurance</button>
                <% end %>
                <% #if @insurance_need_recalculate %>
                    <%= render partial: "/internal/shared/calculate_insurance_menu", locals: {order: @order, button_class: "btn btn-primary dropdown-toggle"} %>
                <% #end %>
                <a class="btn btn-primary" href="<%= external_orders_path %>">Back</a>
                <% if !['PAID'].include?(@order.status) %>
                    <button class="btn btn-primary" type="submit" name="submit" id="submit_cancel" value="cancel">Cancel order</button>
                    <button id="submit_save_and_proceed_to_payment" class="btn btn-primary" type="submit" name="submit" value="save_and_proceed_to_payment" <% if @insurance_need_recalculate %> disabled <% end %> >Save and proceed to payment</button>
                    <!--<button class="btn btn-primary" type="submit" name="submit" id="submit_approval" value="save_and_proceed_to_approval">Save and proceed to approval</button>-->
                <% end %>
            </div>
        </div>
    <% end %>

    <% @order.order_items.each do |order_item| %>
        <% if ['ForeignWorker'].include? order_item.order_itemable_type %>
            <%= render partial: 'internal/orders/fw_form', locals: {order_item: order_item} %>
        <% end %>
    <% end %>
</div>

<%=render 'etr_search_worker' %>

<form action="<%= change_comment_internal_order_path(@order) %>" id="change_comment_form" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    <input type="hidden" name="order_item_id" id="change_comment_order_item_id" value="">
    <input type="hidden" name="comment" id="change_comment_comment" value="">
</form>

<form action="<%= change_fee_internal_order_path(@order) %>" id="change_fee_form" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    <input type="hidden" name="order_item_id" id="change_fee_order_item_id" value="">
    <input type="hidden" name="fee_id" id="fee_id" value="">
</form>

<style>
.plks-optional-message {
    display: <%= has_plks_optional ? "block" : "none" %>;
}
</style>

<% content_for :page_end_scripts do %>
<script>
    $('#submit_cancel').click(function () {
        $('#order_form textarea').prop('disabled', true);
        $('#order_form').submit();
    });

function comment_changed(ta)
{
    $('#change_comment_order_item_id').val(ta.getAttribute("data-order_item_id"));
    $('#change_comment_comment').val($(ta).val());
    $('#change_comment_form').submit();
}

function change_fee(sel)
{
    $('#change_fee_order_item_id').val(sel.getAttribute("data-order-item-id"));
    $('#fee_id').val($(sel).val());
    $('#change_fee_form').submit();
}
</script>
<% end %>