config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# resources standard method: index, new, create, show, edit, update, destroy

require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
    # For nios subdomains.
    constraints :subdomain => ENV["SUBDOMAIN_NIOS"].downcase do
        Sidekiq::Web.use Rack::Auth::Basic do |username, password|
            md5_of_password = Digest::MD5.hexdigest(password)
            username == ENV["SIDEKIQ_USERNAME"] && md5_of_password == ENV['SIDEKIQ_PASSWORD']
        end if !Rails.env.development?
        mount Sidekiq::Web, at: "/sidekiq"

        # logs viewer
        # mount Logster::Web => "/logs"

        # internal module
        scope module: "internal", as: "internal" do
            devise_for :users, as: 'internal', controllers: {
                sessions: 'internal/users/sessions',
                passwords: 'internal/users/passwords',
                confirmations: 'internal/users/confirmations'
                # registrations: 'internal/users/registrations',
            }

            get 'test-sleep/:sleep', to: 'home#test_sleep'
            get 'show-env', to: 'home#show_env'
            get 'ip', to: 'home#ip', as: 'nios_ip'

            resources :countries do
                resources :audits, only: [:index, :show]
            end

            resources :states do
                member do
                    get :postcodes
                    get :towns
                    get :multistatetowns
                end
                resources :audits, only: [:index, :show]
            end

            resources :towns do
                member do
                    get :clinics
                    get :radiologists
                end
                resources :audits, only: [:index, :show]
            end

            # scope "system-configurations", as: 'system_configurations' do
            #     get "", to: 'system_configurations#index'
            #     get "edit", to: 'system_configurations#edit'
            #     put "edit", to: 'system_configurations#update'
            #     get "approval", to: 'system_configurations#approval'
            #     put "approval", to: 'system_configurations#approval_update'
            # end

            resources :system_configurations, only: [:index] do
                collection do
                    get 'system'
                    get 'system_edit'
                    patch 'system_edit', to: 'system_configurations#system_update'
                    get 'system_approval'
                    patch 'system_approval', to: 'system_configurations#system_approval_update'

                    get 'xqcc'
                    get 'xqcc_edit'
                    patch 'xqcc_edit', to: 'system_configurations#xqcc_update'
                    get 'xqcc_approval'
                    patch 'xqcc_approval', to: 'system_configurations#xqcc_approval_update'

                    get 'finance'
                    get 'finance_edit'
                    patch 'finance_edit', to: 'system_configurations#finance_update'
                end

                resources :audits, only: [:index, :show]
            end

            resources :zones do
                resources :audits, only: [:index, :show]
            end

            resources :banks do
                resources :audits, only: [:index, :show]
            end

            resources :fees do
                resources :audits, only: [:index, :show]
            end

            resources :associations do
                resources :audits, only: [:index, :show]
            end

            resources :payment_methods do
                resources :audits, only: [:index, :show]
            end

            resources :change_sp_reasons do
                resources :audits, only: [:index, :show]
            end

            resources :retake_reasons do
                resources :audits, only: [:index, :show]
            end

            resources :block_reasons do
                resources :audits, only: [:index, :show]
            end

            resources :bypass_fingerprint_reasons do
                resources :audits, only: [:index, :show]
            end

            resources :monitor_reasons do
                resources :audits, only: [:index, :show]
            end

            resources :amendment_reasons do
                resources :audits, only: [:index, :show]
            end

            resources :roles
            resources :user_groups
            resources :user_setups do
                collection do
                    get "load_userable_ids/:type", to: "user_setups#load_userable_ids"
                    post 'bulk_action', to: 'user_setups#bulk_action', as: 'bulk_action'
                end
                member do
                    get 'resend-confirmation', to: 'user_setups#resend_confirmation'
                end
                resources :audits, only: [:index, :show]
            end

            # append single get route before organizations/:id catch
            get 'organizations/chart', to: 'organizations#chart'
            get 'organizations/tree', to: 'organizations#tree'
            resources :organizations do
                resources :audits, only: [:index, :show]
            end

            resources :template_variables do
                resources :audits, only: [:index, :show]
            end

            resources :job_types do
                resources :audits, only: [:index, :show]
            end

            resources :laboratory_types do
                resources :audits, only: [:index, :show]
            end

            resources :call_log_case_types do
                resources :audits, only: [:index, :show]
            end

            resources :titles do
                resources :audits, only: [:index, :show]
            end

            resources :fp_devices

            resources :district_health_offices do
                resources :audits, only: [:index, :show]
            end

            resources :employer_types do
                resources :audits, only: [:index, :show]
            end

            resources :appeal_todos do
                resources :audits, only: [:index, :show]
            end

            resources :tcupi_todos do
                resources :audits, only: [:index, :show]
            end

            resources :digital_xray_providers do
                resources :audits, only: [:index, :show]
            end

            resources :insurance_service_providers do
                resources :audits, only: [:index, :show]
            end

            resources :finance_settings do
                resources :audits, only: [:index, :show]
            end

            resources :races do
                resources :audits, only: [:index, :show]
            end

            resources :approval_approvers do
                resources :audits, only: [:index, :show]
            end

            get 'approval_approvers/:category/category_approvers', to: '/internal/approval_approvers#category_approvers', as: "category_approvers"

            resources :bulletins
            resources :clinics
            resources :xray_dispatches
            resources :xray_storages
            resources :activities, only: [:index]

            resources :call_logs do
                collection do
                    get "search_callable"
                end
                resources :call_log_follow_ups
            end

            resources :bank_drafts do
                member do
                    get 'hold'
                    post 'hold', to: 'bank_drafts#hold_update'
                    get 'unhold'
                    patch 'unhold', to: 'bank_drafts#unhold_update'

                    get 'bad'
                    get 'unbad'

                    get 'replace'
                    patch 'replace', to: 'bank_drafts#replace_update'

                    get 'refund'
                    patch 'refund', to: 'bank_drafts#refund_update'
                end

                resources :bd_refunds
            end

            resources :orders do
                member do
                    get 'approval'
                    patch 'approval', to: 'orders#approval_update'

                    get 'payment'
                    patch 'payment', to: 'orders#payment_update'

                    get 'payment/bankdraft', to: 'orders#payment_bankdraft'
                    get 'payment/bankdraft/new', to: 'orders#payment_bankdraft_new'
                    put 'payment/bankdraft', to: 'orders#payment_bankdraft_create'
                    get 'payment/bankdraft/:bank_draft_id/edit', to: 'orders#payment_bankdraft_edit', as: "payment_bankdraft_edit"
                    patch 'payment/bankdraft/:bank_draft_id', to: 'orders#payment_bankdraft_update', as: "payment_bankdraft_update"
                    delete 'payment/bankdraft/:bank_draft_id', to: 'orders#payment_bankdraft_destroy', as: "payment_bankdraft_destroy"
                    get 'payment/bankdraft/:bank_draft_id/add', to: 'orders#payment_bankdraft_add', as: "payment_bankdraft_add"
                    put 'payment/bankdraft/:bank_draft_id/add', to: 'orders#payment_bankdraft_add_update'

                    post 'payment_status'
                    post 'payment_status_backend'

                    post 'change_comment', to: 'orders#change_comment', as: 'change_comment'
                    post 'change_fee', to: 'orders#change_fee', as: 'change_fee'
                    post 'add_fw', to: 'orders#add_fw', as: 'add_fw'
                    get 'remove_fw', to: 'orders#remove_fw', as: 'remove_fw'
                    patch 'update_fw', to: 'orders#update_fw', as: 'update_fw'

                    get "remove-order-item/:oi_id", to: "orders#remove_order_item", as: "remove_order_item"

                    get 'invoice', to: 'orders#invoice', as: 'invoice'

                    get 'requery', to: 'orders#requery', as: 'requery'

app/controllers/internal/activities_controller.rb
class Internal::ActivitiesController < InternalController

    def index
        activities = PublicActivity::Activity

        unless params[:category].blank?

            category_key = get_category_key(params[:category])

            activities = activities.where("key LIKE ?", "%" + category_key + "%")
        end

        unless params[:owner_id].blank?

            owner_id = params[:owner_id]

            activities = activities.where(owner_id: owner_id)

        end

        unless params[:start_date].blank?

            start_date = params[:start_date]

            activities = activities.where("created_at >= ?", start_date)

        end

        unless params[:end_date].blank?

            end_date = params[:end_date]

            activities = activities.where("created_at <= ?", Time.parse(end_date) + 1.day)

        end

        @activities = activities.order(created_at: :desc)
            .page(params[:page])
            .per(get_per)

        # @users = User.all
    end

    def get_category_key(category)
        category_key = "#{category}."
    end

end

app/controllers/internal/amendment_reasons_controller.rb
module Internal
  class AmendmentReasonsController < InternalController
    before_action :set_amendment_reason, only: [:show, :edit, :update, :destroy]

    before_action -> { can_access?("VIEW_AMENDMENT_REASON") }, only: [:index, :show]
    before_action -> { can_access?("CREATE_AMENDMENT_REASON") }, only: [:new, :create]
    before_action -> { can_access?("EDIT_AMENDMENT_REASON") }, only: [:edit, :update]
    before_action -> { can_access?("DELETE_AMENDMENT_REASON") }, only: [:destroy]

    # GET /amendment_reasons
    # GET /amendment_reasons.json
    def index
      @amendment_reasons = AmendmentReason.search_code(params[:code])
     .search_description(params[:name])
     .page(params[:page])
     .per(get_per)
    end

    # GET /amendment_reasons/1
    # GET /amendment_reasons/1.json
    def show
    end

    # GET /amendment_reasons/new
    def new
      @amendment_reason = AmendmentReason.new
    end

    # GET /amendment_reasons/1/edit
    def edit
    end

    # POST /amendment_reasons
    # POST /amendment_reasons.json
    def create
      @amendment_reason = AmendmentReason.new(amendment_reason_params)

      respond_to do |format|
        if @amendment_reason.save
          format.html { redirect_to internal_amendment_reasons_url, notice: 'Amendment reason was successfully created.' }
          format.json { render :show, status: :created, location: @amendment_reason }
        else
          format.html { render :new }
          format.json { render json: @amendment_reason.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /amendment_reasons/1
    # PATCH/PUT /amendment_reasons/1.json
    def update
      respond_to do |format|
        if @amendment_reason.update(amendment_reason_params)
          format.html { redirect_to internal_amendment_reasons_url, notice: 'Amendment reason was successfully updated.' }
          format.json { render :show, status: :ok, location: @amendment_reason }
        else
          format.html { render :edit }
          format.json { render json: @amendment_reason.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /amendment_reasons/1
    # DELETE /amendment_reasons/1.json
    def destroy
      @amendment_reason.destroy
      respond_to do |format|
        format.html { redirect_to internal_amendment_reasons_url, notice: 'Amendment reason was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_amendment_reason
        @amendment_reason = AmendmentReason.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def amendment_reason_params
        params.require(:amendment_reason).permit(:code, :name)
      end
  end
end

app/controllers/internal/appeal_todos_controller.rb
class Internal::AppealTodosController < InternalController
  before_action :set_appeal_todo, only: [:show, :edit, :update, :destroy]

  # GET /appeal_todos
  # GET /appeal_todos.json
  def index
    @appeal_todos = AppealTodo.search_description(params[:description])
    .page(params[:page])
    .per(get_per)
  end

  # GET /appeal_todos/1
  # GET /appeal_todos/1.json
  def show
  end

  # GET /appeal_todos/new
  def new
    @appeal_todo = AppealTodo.new
  end

  # GET /appeal_todos/1/edit
  def edit
  end

  # POST /appeal_todos
  # POST /appeal_todos.json
  def create
    @appeal_todo = AppealTodo.new(appeal_todo_params)

    respond_to do |format|
      if @appeal_todo.save
        format.html { redirect_to internal_appeal_todos_url, notice: 'Appeal todo was successfully created.' }
        format.json { render :show, status: :created, location: @appeal_todo }
      else
        format.html { render :new }
        format.json { render json: @appeal_todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appeal_todos/1
  # PATCH/PUT /appeal_todos/1.json
  def update
    respond_to do |format|
      if @appeal_todo.update(appeal_todo_params)
        format.html { redirect_to internal_appeal_todos_url, notice: 'Appeal todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @appeal_todo }
      else
        format.html { render :edit }
        format.json { render json: @appeal_todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appeal_todos/1
  # DELETE /appeal_todos/1.json
  def destroy
    @appeal_todo.destroy
    respond_to do |format|
      format.html { redirect_to internal_appeal_todos_url, notice: 'Appeal todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appeal_todo
      @appeal_todo = AppealTodo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appeal_todo_params
      params.require(:appeal_todo).permit(:description, :is_active)
    end
end

app/views/internal/laboratory_types/_filter.html.erb
<div class="card">
    <div class="card-header">
        <strong>Filter</strong>
    </div>

    <%= form_tag internal_laboratory_types_path, method: 'get' do |form| %>
        <%= hidden_field_tag :per, params[:per] || get_per_options.first %>
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group row">
                        <label for="name" class="col-sm-3 col-form-label">Name</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="name" id="name" value="<%= params[:name] %>">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="text-right">
                <%=raw filter_clear_button internal_laboratory_types_path %>
                <%=raw filter_button %>
            </div>
        </div>
    <% end %>
</div>

app/views/internal/laboratory_types/_form.html.erb
<div class="card-body">

    <%= render 'shared/all_validation_flash', { model_obj: @laboratory_type } %>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <%= form.label :name, class: 'required' %>
                <%= form.text_field :name, class: 'form-control', required: true %>
            </div>
        </div>
    </div>

</div>

<div class="card-footer">

    <div class="text-right">
        <%=raw edit_back_button(internal_laboratory_types_path) %>
        <%=raw edit_save_button() %>
    </div>

</div>

app/views/internal/laboratory_types/edit.html.erb
<div class="card">
    <div class="card-header">
        <strong>LaboratoryTypes</strong> - Edit LaboratoryType
    </div>
    <%= form_for @laboratory_type, url: internal_laboratory_type_path(@laboratory_type), html: {class: "#{params[:action]}_laboratory_type laboratory_type-form with-parsley"} do |form| %>
        <%= render 'form', { form: form } %>
    <% end %>
</div>

app/views/internal/laboratory_types/index.html.erb
<div class="card">
    <div class="card-header">
        <strong>Laboratory Types</strong>
    </div>

    <!-- card-body -->
    <div class="card-body">
        <%=render "filter" %>

        <%=render '/shared/all_flash' %>

        <div class="row">
            <div class="col module-actions text-right">
                <% if has_permission?('CREATE_LABORATORY_TYPE') %>
                    <%=raw index_table_new_button(new_internal_laboratory_type_path) %>
                <% end %>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="<%= index_table_class %>">
                    <thead>
                    <tr>
                      <th class="module-row-numbers">#</th>
                      <th>Name</th>
                      <th class="module-row-actions">Action(s)</th>
                    </tr>
                    </thead>

                    <tbody>
                    <% if @laboratory_types.blank? %>
                      <tr>
                        <td colspan="3" class="text-danger">No records found.</td>
                      </tr>
                    <% else %>

                      <% @laboratory_types.each.with_index((@laboratory_types.current_page - 1) * get_per + 1) do |laboratory_type, index| %>
                        <tr>
                          <td class="module-row-numbers"><%= index %></td>
                          <td><%= laboratory_type.name %></td>
                          <td class="module-row-actions">
                            <%=raw index_table_show_button(internal_laboratory_type_path(laboratory_type)) %>
                            <% if has_permission?('EDIT_LABORATORY_TYPE') %>
                              <%=raw index_table_edit_button edit_internal_laboratory_type_path(laboratory_type) %>
                            <% end %>
                            <% if has_permission?('DELETE_LABORATORY_TYPE') %>
                              <%=raw index_table_delete_button(internal_laboratory_type_path(laboratory_type)) %>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>

                    <% end %>
                    </tbody>
                  </table>
                </div>
            </div>
        </div>
        <div class="row">
            <%= paginate @laboratory_types %>
        </div>
    </div>
    <!-- /card-body -->
</div>

app/views/internal/laboratory_types/new.html.erb
<div class="card">
    <div class="card-header">
        <strong>Laboratory Types</strong> - New Laboratory Type
    </div>
    <%= form_for @laboratory_type, url: internal_laboratory_types_path, html: {class: "#{params[:action]}_laboratory_type laboratory_type-form with-parsley"} do |form| %>
        <%= render 'form', { form: form } %>
    <% end %>
</div>

app/views/internal/laboratory_types/show.html.erb
<div class="card">

    <div class="card-header">
        <strong>Laboratory Types</strong> - Laboratory Type Detail
    </div>

    <div class="card-body">

        <%=render '/shared/all_flash' %>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label for="laboratory_type_code">Name</label>
                    <p class="form-control-plaintext">
                        <%= @laboratory_type.name %>
                    </p>
                </div>
            </div>
        </div>

    </div>

    <div class="card-footer">

        <div class="text-right">
            <%=raw show_back_button(internal_laboratory_types_path) %>
            <% if has_permission?('EDIT_LABORATORY_TYPE') %>
                <%=raw show_edit_button(edit_internal_laboratory_type_path(@laboratory_type)) %>
            <% end %>
        </div>

    </div>

</div>
<!-- /.card -->

<div class="card">
    <div class="card-body">
        <ul class="list-group">
            <% if has_permission?("VIEW_AUDIT_LABORATORY_TYPE") %>
                <li class="list-group-item">
                    <%= link_to "Audits", internal_laboratory_type_audits_path(@laboratory_type) %>
                </li>
            <% end %>
        </ul>
    </div>
</div>